
# parsetab_re.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xe3\xf7\x1b^\x13\xcdAc\xfa\xaan\xef\x88\x91db'
    
_lr_action_items = {'UCHAR':([2,3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[3,-19,-7,-20,-33,15,-6,-21,-4,-5,24,-12,-16,-17,-18,-14,-13,-11,-15,34,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),'BACKSLASH':([2,3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[8,-19,-7,-20,-33,17,-6,-21,-4,-5,8,-12,-16,-17,-18,-14,-13,-11,-15,8,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),'DIVIDE':([0,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[2,-19,-7,-20,-33,14,16,-6,-21,-4,-5,25,-12,-16,-17,-18,-14,-13,-11,-15,-2,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),'ID_PART':([2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,],[10,-19,-7,-20,-33,18,-6,-21,-4,-5,31,-37,-12,-16,-17,-18,-14,-13,-11,-15,40,-26,-29,-35,-31,-32,-27,-28,-30,-34,42,-22,-10,-23,-3,-24,-9,-25,-8,-36,]),'RSBRACKET':([2,3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[5,-19,-7,-20,-33,19,-6,-21,-4,-5,27,-12,-16,-17,-18,-14,-13,-11,-15,36,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),'LSBRACKET':([2,3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[6,-19,-7,-20,-33,20,-6,-21,-4,-5,29,-12,-16,-17,-18,-14,-13,-11,-15,6,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),'$end':([1,14,33,42,],[0,-37,-1,-36,]),'STAR':([3,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,],[-19,-7,-20,-33,22,-6,-21,-4,-5,30,-12,-16,-17,-18,-14,-13,-11,-15,38,-26,-29,-35,-31,-32,-27,-28,-30,-34,-22,-10,-23,-3,-24,-9,-25,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re_lit':([0,],[1,]),'re_expr_class':([2,23,],[4,35,]),'re_chars':([11,],[23,]),'re_class_chars':([6,],[13,]),'re_class_char':([13,],[28,]),'re_non_term':([8,],[21,]),'re_body':([2,],[7,]),'re_flags':([14,],[33,]),'re_char':([23,],[37,]),'re_backlash_seq':([2,13,23,],[9,26,39,]),'re_first_char':([2,],[11,]),'re_non_term_restrict3':([13,],[32,]),'re_non_term_restrict2':([23,],[41,]),'re_non_term_restrict1':([2,],[12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re_lit","S'",1,None,None,None),
  ('re_lit -> DIVIDE re_body DIVIDE re_flags','re_lit',4,'p_re_lit','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',51),
  ('re_body -> re_first_char re_chars','re_body',2,'p_re_body','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',56),
  ('re_chars -> re_chars re_char','re_chars',2,'p_re_chars','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',61),
  ('re_chars -> <empty>','re_chars',0,'p_re_chars','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',62),
  ('re_first_char -> re_non_term_restrict1','re_first_char',1,'p_re_first_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',71),
  ('re_first_char -> re_backlash_seq','re_first_char',1,'p_re_first_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',72),
  ('re_first_char -> re_expr_class','re_first_char',1,'p_re_first_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',73),
  ('re_char -> re_non_term_restrict2','re_char',1,'p_re_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',79),
  ('re_char -> re_backlash_seq','re_char',1,'p_re_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',80),
  ('re_char -> re_expr_class','re_char',1,'p_re_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',81),
  ('re_backlash_seq -> BACKSLASH re_non_term','re_backlash_seq',2,'p_re_backlash_seq','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',87),
  ('re_non_term -> UCHAR','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',92),
  ('re_non_term -> LSBRACKET','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',93),
  ('re_non_term -> RSBRACKET','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',94),
  ('re_non_term -> STAR','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',95),
  ('re_non_term -> DIVIDE','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',96),
  ('re_non_term -> BACKSLASH','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',97),
  ('re_non_term -> ID_PART','re_non_term',1,'p_re_non_term','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',98),
  ('re_non_term_restrict1 -> UCHAR','re_non_term_restrict1',1,'p_re_non_term_restrict1','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',103),
  ('re_non_term_restrict1 -> RSBRACKET','re_non_term_restrict1',1,'p_re_non_term_restrict1','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',104),
  ('re_non_term_restrict1 -> ID_PART','re_non_term_restrict1',1,'p_re_non_term_restrict1','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',105),
  ('re_non_term_restrict2 -> UCHAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',110),
  ('re_non_term_restrict2 -> RSBRACKET','re_non_term_restrict2',1,'p_re_non_term_restrict2','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',111),
  ('re_non_term_restrict2 -> STAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',112),
  ('re_non_term_restrict2 -> ID_PART','re_non_term_restrict2',1,'p_re_non_term_restrict2','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',113),
  ('re_non_term_restrict3 -> UCHAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',119),
  ('re_non_term_restrict3 -> LSBRACKET','re_non_term_restrict3',1,'p_re_non_term_restrict3','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',120),
  ('re_non_term_restrict3 -> STAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',121),
  ('re_non_term_restrict3 -> DIVIDE','re_non_term_restrict3',1,'p_re_non_term_restrict3','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',122),
  ('re_non_term_restrict3 -> ID_PART','re_non_term_restrict3',1,'p_re_non_term_restrict3','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',123),
  ('re_expr_class -> LSBRACKET re_class_chars RSBRACKET','re_expr_class',3,'p_re_expr_class','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',128),
  ('re_class_chars -> re_class_chars re_class_char','re_class_chars',2,'p_re_class_chars','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',134),
  ('re_class_chars -> <empty>','re_class_chars',0,'p_re_class_chars','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',135),
  ('re_class_char -> re_non_term_restrict3','re_class_char',1,'p_re_class_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',144),
  ('re_class_char -> re_backlash_seq','re_class_char',1,'p_re_class_char','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',145),
  ('re_flags -> re_flags ID_PART','re_flags',2,'p_re_flags','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',151),
  ('re_flags -> <empty>','re_flags',0,'p_re_flags','c:\\dev\\allshape\\tools\\altdart\\AltDart\\regexpr_parse.py',152),
]
